# -*- coding: utf-8 -*-
"""Data_Exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13a4pUj71RbrmE0R5glsNZJeefTav_onp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error as mse
import tensorflow as tf
from tensorflow import keras
import xgboost as xgb

data = pd.read_csv('https://www.dropbox.com/s/hdiyuipgmas8w3h/supercon.csv?dl=1')

data.shape

data.head(20)
#print(data.isna().sum().sum())

for x in data.dtypes:
  print(x)

sb.pairplot(data, x_vars=["mean_atomic_mass", "mean_fie", "mean_atomic_radius", "mean_Density", "mean_ElectronAffinity", "mean_FusionHeat", "mean_ThermalConductivity", "mean_Valence" ], y_vars="critical_temp")